name: Build and Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./25-platzi-conf-merch
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./25-platzi-conf-merch/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./25-platzi-conf-merch
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: ./25-platzi-conf-merch/dist
      - name: Deploy to Firebase
        
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "DanielGeek/react_proyectos/25-platzi-conf-merch/"